---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: myconfigmap
  namespace: default
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: resources
    repoURL: "https://github.com/christian-heusel/test123.git"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
